### ISSUE TITLE
Infinite fall

### ISSUE THREAD

**Issue by barekun** [LeonBlade/HeelsPlugin#1]
I tried the plugin and so far everytime i set an offset my character go out of bounds into an infinite fall and i have to restart the game. Tried 4 times in diferent locations (Limsa, squadron room and crystarium) and with different offsets (0.11-0.20) with a viera character.

**Comment by LeonBlade** [comment]
Can you try a negative number and let me know what happens?

**Comment by barekun** [comment]
Didnt work. It put me around 10 meters below the floor. I tried -0.11.

**Comment by LeonBlade** [comment]
So both positive and negative numbers put you below the ground?

**Comment by barekun** [comment]
Well positive numbers put me so out of bounds that i couldnt even tell if i was above or below the floor, only the typical infinite fall with some background.

**Comment by alucard1054** [comment]
I can't get Heels plugin to work anymore. After 5.4 patch. I've reinstalled it. Also reinstalled launcher. What am i missing? it was for a while giving me .disabled

**Comment by xDIchigo99** [comment]
I also have the Problem that the Plugin doesen't work for me and i fall of the ground after i try to walk.

**Comment by LeonBlade** [comment]
The latest release will fix this issue.
