### ISSUE TITLE
the latest version (1.19) makes CN client crash

### ISSUE THREAD

**Issue by Orghana** [LeonBlade/HeelsPlugin#10]
installing the heels plugin ver1.19 from Dalamud will immediately kill the game and it will crash again when I try to relaunch the game. the only way to launch the game is to delete the heels plugin in the Dalamud folder. no error code or anything, the game just disappears with the heels plugin installed.

**Comment by LeonBlade** [comment]
Thanks for the report, I will look into this.

**Comment by LeonBlade** [comment]
I believe it has to do with the change to .NET 6 with the latest update. I would suggest not updating the plugin.

**Comment by Orghana** [comment]
alright, thank you very much!
