### ISSUE TITLE
API Request for Mare Synchronos

### ISSUE THREAD

**Issue by happilysleeping** [LeonBlade/HeelsPlugin#11]
There's now a plugin that allows syncing mods between players called mare synchronos ( https://github.com/Penumbra-Sync/server ), and it would be awesome if there was a way for these two plugins to interface. its dev says if there is an api of some sort, he could integrate it. not sure what the scope of that would be, but figured i would ask since i love being tall as hell in my stilletos.

thank you very much either way for your hard work!

**Comment by LeonBlade** [comment]
I've spoken to them before, I would like to support this as well. I will look into doing this soon. Thank you!

**Comment by AkenoSkye** [comment]
Yes please!!

**Comment by LeonBlade** [comment]
Support for Mare will be/is included in the 0.4.2 update!
