### ISSUE TITLE
Some filters do not properly work.

### ISSUE THREAD

**Issue by Herbalicious** [LeonBlade/HeelsPlugin#17]
This may be getting fucked with due to glamourer? Assuming that it worked at one point, I have no idea how it could have gotten this fucked up, but... this is how it works on my client.

- The Hyur filter works as intended.
- The Elezen filter does not work; Elezen are instead affected by the Lalafell filter.
- The Miqote filter does not work; Miqote are instead affected by the Roegadyn filter.
- The Roegadyn filter does not fully work; filters must include Hyur, Miqote, _and_ Roegadyn to affect Roegadyn.
- The AuRa filter does not fully work; filters must include AuRa _and_ Lalafell to affect AuRa.
- The Hrothgar filter does not work; filters must include Hyur, Roegadyn, and AuRa to affect Hrothgar.
- The Viera filter works as intended.
- The gender filters work as intended.

**Comment by LeonBlade** [comment]
Thank you for testing this and logging this report.

**Comment by LeonBlade** [comment]
Thank you again, this is fixed in version 1.3.1
