### ISSUE TITLE
Config crash

### ISSUE THREAD

**Issue by kelseyanne123** [LeonBlade/HeelsPlugin#19]
Hello! every time I try to open the config my game crashes. I've tried to uninstall from the pulgins menu in game, and also delete the file myself from the plugins folder to have a 100% fresh install and it has not fixed it.  here is my log https://drive.google.com/file/d/1OU3CMmo4DIH7QYik3_MgYgi0xJwpugiz/view?usp=sharing

**Comment by SuneReKai** [comment]
I have the same issue as well.

**Comment by LeonBlade** [comment]
Can you include your config somewhere? The log doesn't show anything of value, instead it shows some other errors with "MapLink".

**Comment by LeonBlade** [comment]
I would just delete your config file and start the plugin again.
