### ISSUE TITLE
gposeActorFunc not compatible with CN client

### ISSUE THREAD

**Issue by Bluefissure** [LeonBlade/HeelsPlugin#2]
In CN client the [sig of gposeActorFunc](https://github.com/LeonBlade/HeelsPlugin/blob/main/HeelsPlugin/PluginMemory.cs#L35) should be `48 89 5C 24 10 48 89 6C 24 18 56 41 54 41 55 41 56 41 57 48 81 EC 80`.

BTW, I use the SigMaker plugin in ida and it generated `E8 ?? ?? ?? ?? 48 8B D8 48 85 DB 74 33` as the direct reference, which may be compatible with both clients I suppose.

**Comment by LeonBlade** [comment]
Thanks, I'll try it out soon.
