### ISSUE TITLE
Offset not reflecting ingame

### ISSUE THREAD

**Issue by 343-Daedalus** [LeonBlade/HeelsPlugin#23]
Hello

I have updated the plugin for 6.3 but when I try to set a value to offset a footwear, it does not reflect in game.
I have tried  reinstalling everything but it changed nothing.
Unless I am missing something obvious it seems the plugin is not working for me.

**Comment by xshockx** [comment]
same issue for me

**Comment by xcarolinexx** [comment]
@343-Daedalus how did you update the plugin ? is not supposed to wait for the automatic update ?

**Comment by ohsnapitsmama** [comment]
Same issue here; I've reinstalled, redone my entries, and try disabling and enabling the plugin itself.

**Comment by ohsnapitsmama** [comment]
@xcarolinexx I had to delete the plugin from dalamud and re-add it manually because dalamud wouldn't update it despite the github saying the update was released yesterday.

**Comment by xcarolinexx** [comment]
so it was an update, ty ! but i guess we will have to wait more

**Comment by julyxiv** [comment]
having the same issue here.

i didn't have the plugin installed until after the patch, and even after plugins were re-enabled, dalamud didn't allow me to install it at first, saying it was outdated. eventually it did let me install it as if it had been updated, but the version number displays as v1.2.5 which according to github was released on december 10th (and still says it's the most recent release).

not being a coder myself i have no idea if any of this is relevant to why it's not working, but i thought i should point it out just in case.

**Comment by LeonBlade** [comment]
There is just an issue with the GH actions, it needs to be fixed and the version will be deployed properly.
