### ISSUE TITLE
Doesn't work in Cutscenes

### ISSUE THREAD

**Issue by SevereArtisan** [LeonBlade/HeelsPlugin#28]
Plugin works just fine out in the open world, but it seems to be iffy for cutscenes like during the MSQ. Sometimes it works, sometimes I don't think it does. I notice my character either floating a bit off the ground with one gearpiece sometimes in a cutscene that I configured to be lower. Whereas with another, I see them sinking a bit into the ground even though I set it to be higher.

Not sure if this is a known issue/problem already or no or whether it's just the game's terrain and being on uneven ground.

**Comment by LeonBlade** [comment]
Not much I can really do about this as cutscenes are a completely different part of the game. I don't think I'm really that concerned with getting it to work in cutscenes either.
