### ISSUE TITLE
Dalamund not supported

### ISSUE THREAD

**Issue by Pandaeyes86** [LeonBlade/HeelsPlugin#35]
Hello 
I love your addon which makes wearing heels in game easier to use, instead of sinking into the floor while playing, however im awear its not supported by dalamund and is a private project. I made the mistake of asking in dalamund discord why your plugin had vanished and how to get it back and got told to speak to you directly. How do i add you back to my plugins for dalamund / xivlauncher? ive got your url installed and everything but your not showing up to add. Thank you.

**Comment by LeonBlade** [comment]
Please check out the readme on this repo for the installation instructions.
