### ISSUE TITLE
Automatic change feature request

### ISSUE THREAD

**Issue by Alkor1** [LeonBlade/HeelsPlugin#4]
I like the idea of this plugin, but changing the setting for every kind of high heel or flat shoes one will quickly feel tedious.
Would it be possible to make a list of shoes and affect the offset in the list, so the program can apply the change whenever we change shoes ?

**Comment by LeonBlade** [comment]
I've had this requested before, I think a simple list like this is completely fine. I'll implement this.

**Comment by LeonBlade** [comment]
Added this in the latest version.
