### ISSUE TITLE
Unable to apply offset to same model items

### ISSUE THREAD

**Issue by Lgutsfeld** [LeonBlade/HeelsPlugin#6]
With this latest version I'm unable to apply an offset to certain items that share a model.

Example:
Selecting 'Edenchoir Boots of Casting' (variant 2) or 'Edencall Boots of Casting' defaults back to 'Edenchoir Boots of Healing' (variant 1) and will not apply an offset to the casting versions, even though they share the same model. This used to work just fine before EW.

**Comment by LeonBlade** [comment]
Thanks for testing, I had to change something so I'll double check with this and see if I can figure out a solution for it.

**Comment by LeonBlade** [comment]
New update `1.1.3` should fix this issue. A change was made to allow for variants and legacy support for the old config system going forward. All you need to do is just select the item you want again and it should work.
