### ISSUE TITLE
Issue with ''set as your active footwear''

### ISSUE THREAD

**Issue by Tempest1202** [LeonBlade/HeelsPlugin#7]
I clicked the button cause i was curious then my added items vanished, then i tryd to fix it and made it worse with clicking the same button 2 more times .... deinstalled the Addon manually and even resetet the Settings and it still looks like this and i cant add new Items 
![1](https://user-images.githubusercontent.com/102912320/161432930-2606c686-ac3d-435d-b0bb-a5c510242dc7.PNG)
.

**Comment by LeonBlade** [comment]
Thank you for the report. I'm aware of this issue, I'll be working on a fix soon. If you know which footwear you were using while doing this it will help.

**Comment by Tempest1202** [comment]
Yea i had 2 footwears put into it 1x the Frontier Pumplets and 1x Bootlets of Eternal Devotion, active i had the Bootles at the time

**Comment by LeonBlade** [comment]
I just released an update that should fix this partially. If it detects the footwear incorrectly, it will be able to fail gracefully. I am not able to reproduce this issue myself, so I will have to monitor it going forward. Thank you.

**Comment by LeonBlade** [comment]
The most recent update fully fixes this issue, another user had noticed it was due to the earring slow (an issue with how I was reading in the footwear). This issue should be fully fixed in the latest version.

**Comment by Tempest1202** [comment]
Will check it out once i go to my PC when im awake again, then close the ticket <3 Incase it doesnt work i will provide more information's from my side ^-^
